name: Deploy Power Apps Solution

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub runner using Ubuntu

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Power Platform CLI (pac CLI)
      - name: Set up Power Platform CLI
        uses: microsoft/powerplatform-actions/setup@v1
        with:
          pac-version: 'latest'  # Install the latest version of Power Platform CLI

      # Step 3: Authenticate to Power Platform
      - name: Authenticate to Power Platform
        uses: microsoft/powerplatform-actions/authenticate@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          authority-url: 'https://login.microsoftonline.com/${{ secrets.TENANT_ID }}'
          environment-url: ${{ secrets.ENVIRONMENT_URL }}

      # Step 4: Export Solution
- name: Export Solution
  run: pac solution export --name "solution1testing" --path "./solutions/solution.zip"

# Step 5: Import Solution
- name: Import Solution
  run: pac solution import --path "./solutions/solution.zip" --overwrite-unmanaged
